---
Title: "Homework 2"
Subtitle: "Submission 2"
Author: "Alekhya Pidugu"
format:
  pdf:
    output-file: "pidugu-a-hwk1-2"
    output-ext:  "pdf"
---
```{r}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, dplyr, lubridate, readr, readxl, hrbrthemes, fixest,
               scales, gganimate, gapminder, gifski, png, tufte, plotly, OECD,
               ggrepel, survey, foreign, devtools, pdftools, kableExtra, modelsummary,
               kableExtra)

```
```{r}
# Load data from .RData file
load("/Users/alekhyapidugu/Desktop/Homework2/Submission2/Hwk2_workspace.Rdata")
```
```{r}
#| echo: false
```
```{r results="hide", echo=FALSE, message=FALSE}
library(readr)
library(dplyr)
library(lubridate)
# Load the HCRIS data
final.hcris.data <- read_rds("data/output/HCRIS_Data.rds")
```

\newpage
#Question 1
```{r results="hide", echo=FALSE, message=FALSE}
final.hcris.v1996=read_rds('output/HCRIS_Data_v1996.rds')
final.hcris.v2010=read_rds('output/HCRIS_Data_v2010.rds')

## create missing variables for columns introduced in v2010 of hcris forms
final.hcris.v1996 = final.hcris.v1996 %>%
  mutate(hvbp_payment=NA, hrrp_payment=NA)

## combine v1996 and v2010 hcris forms, and sort by provider_number/year
final.hcris=rbind(final.hcris.v1996,final.hcris.v2010) %>%
  mutate(fy_end=mdy(fy_end),fy_start=mdy(fy_start),
         date_processed=mdy(date_processed),date_created=mdy(date_created),
         tot_discounts=abs(tot_discounts), hrrp_payment=abs(hrrp_payment)) %>%
  mutate(fyear=year(fy_end)) %>%
  arrange(provider_number,fyear) %>%
  select(-year)

## count of hospitals/provider_number by year
final.hcris %>% group_by(fyear) %>% count()

# Clean data --------------------------------------------------------------

## create count of reports by hospital fiscal year
final.hcris =
  final.hcris %>% 
  add_count(provider_number, fyear, name="total_reports")

## create running total of reports
final.hcris =
  final.hcris %>% 
  group_by(provider_number, fyear) %>%
  mutate(report_number=row_number())

## identify hospitals with only one report per fiscal year 
## this will be the first set of hospitals in the final dataset
unique.hcris1 =
  final.hcris %>%
  filter(total_reports==1) %>%
  select(-report, -total_reports, -report_number, -npi, -status) %>%
  mutate(source='unique reports')


## identify hospitals with multiple reports per fiscal year
duplicate.hcris = 
  final.hcris %>%
  filter(total_reports>1) %>%
  mutate(time_diff=fy_end-fy_start)

library(ggplot2)

# Plot the number of hospitals with multiple reports over time
hospitals_over_time <- duplicate.hcris %>%
  group_by(fyear) %>%
  summarise(num_hospitals = n())

ggplot(hospitals_over_time, aes(x = fyear, y = num_hospitals)) +
  geom_line() +
  labs(x = "Fiscal Year", y = "Number of Hospitals with Multiple Reports") +
  ggtitle("Hospitals with Multiple Reports in the Same Year")

```
\newpage
#Question 2
```{r}
`r format(unique_count, big.mark=",")` unique reports
```


